
version: "3"
services:
  route:
    build:
      context: .
      dockerfile: router.Dockerfile
    ports:
      - 3000:80
  simple:
    build:
      context: .
      dockerfile: simple.Dockerfile
    ports:
      - 4000:80
  step:
    build:
      context: .
      dockerfile: step.Dockerfile
    ports:
      - 3003:80
  oss:
    build:
      context: .
      dockerfile: oss.Dockerfile
      args:
        - ACCESS_KEY_ID
        - ACCESS_KEY_SECRET
        - ENDPOINT=oss-cn-hangzhou.aliyuncs.com
    ports:
      - 8000:80

